### ISSUE TITLE
Debain Sid ...it's Red

### ISSUE THREAD

**Issue by mexsudo** [jxai/lean-conky-config#10]
Sid updated to Conky 1.18.0-1 yesterday
now my lean-conky is all red... except the progress bar which is still white.

![lean-conky 2023-02-21 07-40-50](https://user-images.githubusercontent.com/7226539/220391332-6f4658e3-196e-4079-b8d8-23b3ec75ddb2.png)

**Comment by mexsudo** [comment]
conky from terminal:
![conky 2023-02-21 08-26-39](https://user-images.githubusercontent.com/7226539/220403059-00d5d1f8-37fb-4b74-bf7c-2478fa1d21dd.png)

**Comment by mexsudo** [comment]
![conky 2023-02-21 08-29-55](https://user-images.githubusercontent.com/7226539/220403709-ba8ea28f-4692-47b4-80f8-8df05a82570a.png)

**Comment by Hanaasagi** [comment]
![2023-03-01_10-06](https://user-images.githubusercontent.com/9482395/222026275-b16ab46d-8ebc-4a2b-ba8b-d38f743b1b53.png)

I met the same problem in a recent rolling update. Looks like version 1.18.1 conflicts with some configurations.

```conky -v
conky 1.18.1_pre compiled 2023-02-24 for Linux x86_64
```

**Comment by Hanaasagi** [comment]
@mexsudo #13 This will be worked.

**Comment by mexsudo** [comment]
> @mexsudo #13 This will be worked.

thank you.
that fixed it

**Comment by mexsudo** [comment]
![555555 color mode 2023-03-01 04-58-19](https://user-images.githubusercontent.com/7226539/222146014-a0f36ea4-e070-4295-9cec-d3603a612211.png)
