### ISSUE TITLE
Feature Request: Graphics Card monitoring

### ISSUE THREAD

**Issue by CHOWY0152** [jxai/lean-conky-config#11]
Hi, 

Thanks for developing this wonderful conky config that just works. Wondering if there is any plan on adding the graphic card monitoring to it? 

Thanks

**Comment by jxai** [comment]
Support for Nvidia GPUs is under development, please stay tuned, thanks.

**Comment by jxai** [comment]
Available in the latest release 0.8.0, enjoy.

**Comment by jxai** [comment]
Supported with v0.8.0.
