### ISSUE TITLE
The visual display of network speed data failed.

### ISSUE THREAD

**Issue by AntsCodeCommunity** [jxai/lean-conky-config#12]
![LCC-CONKY-BUG](https://user-images.githubusercontent.com/70638841/221476716-30457ab5-abd5-4da8-8ebc-fad2b5492922.png)

**Comment by Zeggpold** [comment]
Maybe caused by [this conky bug](https://github.com/brndnmtthws/conky/issues/1109), which unfortunately seems to have been closed without being fixed.

**Comment by jxai** [comment]
Duplicate of #8

**Comment by jxai** [comment]
Duplicate of #8
