### ISSUE TITLE
LCC font Icons

### ISSUE THREAD

**Issue by 4Gettt25** [jxai/lean-conky-config#14]
so I got the config to work on startup on my fedora but I noticed it doesn't use the right font for the icons and I havn't gotten it to work, any tips? 

I tried changing the font in the conky.config to the leanconky font and that worked so it is just the Icons I can' seem to get to work.

**Comment by jxai** [comment]
Did you install the font according to the doc? The config doesn't need to be changed, if the font was installed correctly, it should work.

**Comment by GustavoJST** [comment]
I'm also having the same problem. The LCC icons and the LCC clock font aren't working in a fresh install (I didn't touch in any of the config files or used a local.conf from the local.conf.example).

OS: EndeavourOS (KDE Plasma)
Conky: v1.19.1
LCC: v0.8.0

When running the start-lcc.sh script, it says that the font was installed sucessfully, or that the font was already installed (after the first run), but it doesn't seem to use it. Tried to rebuild the font cache using ```fc-cache -f -v``` and manualy installing the LCC font, but neither worked.

Some screenshots of the issue:
![error](https://user-images.githubusercontent.com/91852186/231639136-df92e800-a9bc-4fa8-87e0-7b69fd187bf2.png)

![font](https://user-images.githubusercontent.com/91852186/231639198-f7fc488e-bd20-481a-8981-4d2154f2e105.png)

**Comment by jxai** [comment]
What does `fc-list |grep Lean` say?

**Comment by GustavoJST** [comment]
> What does `fc-list |grep Lean` say?

![fc-list](https://user-images.githubusercontent.com/91852186/231860655-03ffbceb-8686-4ee1-84b8-96ae99cd717a.png)

Through Plasma:
![plasma](https://user-images.githubusercontent.com/91852186/231859090-d6a91601-133f-4494-b5fc-66ce2d8335c5.png)

**Comment by 4Gettt25** [comment]
/home/felixg/.fonts/lean-conky-config.otf: LeanConkyConfig:style=Regular
/home/felixg/.local/share/fonts/lean-conky-config.otf: LeanConkyConfig:style=Regular
this is the output of fc-list |grep Lean

**Comment by jxai** [comment]
It is strange, your `fc-list` result showed that the font was successfully registered in your system. You might want to play with other non-system fonts to see if conky can use them properly.

**Comment by kojilin** [comment]
Have the same problem. If I remove/comment out the line at https://github.com/jxai/lean-conky-config/blob/27aeeb9c793ad3da8d1da9b777522eef9000e2df/conky.conf#L144, then it works.

Tried to add the print like
```
print('fc-list -f "%{family[0]}" "' .. font .. '"')
local s = utils.sys_call('fc-list -f "%{family[0]}" "' .. font .. '"', true)
print(s)
```
the output is

```
fc-list -f "%{family[0]}" "LeanConkyConfig"

```
`s` is empty.

And if I use command at terminal, the result is

```
❯ fc-list -f "%{family[0]}" "LeanConkyConfig"
LeanConkyConfig⏎ 
```
My env
```
Linux arch 6.2.11-arch1-1
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
fontconfig version 2.14.2
```

**Comment by GustavoJST** [comment]
> Have the same problem. If I remove/comment out the line at
> 
> https://github.com/jxai/lean-conky-config/blob/27aeeb9c793ad3da8d1da9b777522eef9000e2df/conky.conf#L144
> 
> , then it works.
> Tried to add the print like
> 
> ```
> print('fc-list -f "%{family[0]}" "' .. font .. '"')
> local s = utils.sys_call('fc-list -f "%{family[0]}" "' .. font .. '"', true)
> print(s)
> ```
> 
> the output is
> 
> ```
> fc-list -f "%{family[0]}" "LeanConkyConfig"
> ```
> 
> `s` is empty.
> 
> And if I use command at terminal, the result is
> 
> ```
> ❯ fc-list -f "%{family[0]}" "LeanConkyConfig"
> LeanConkyConfig⏎ 
> ```
> 
> My env
> 
> ```
> Linux arch 6.2.11-arch1-1
> Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
> fontconfig version 2.14.2
> ```

This workaround worked greatly. Thanks for sharing. All icons now appear properly.

I tried to switch the font being used by LCC, like @jxai said, but didn't manage to get the icons working.
I then tested LCC on three newly created VMs:
- Ubuntu
- EndeavourOS KDE;
- EndeavourOS Gnome;
- Manjaro KDE.

While LCC worked flawlessly on the Ubuntu VM, the icon problem appear on all other VMs. Maybe LCC icons break on non Ubuntu based systems?

**Comment by kojilin** [comment]
looks like  https://github.com/jxai/lean-conky-config/blob/27aeeb9c793ad3da8d1da9b777522eef9000e2df/lib/utils.lua#L270 got new line inside.
saw https://github.com/jxai/lean-conky-config/blob/27aeeb9c793ad3da8d1da9b777522eef9000e2df/lib/utils.lua#LL261C43-L261C43 `\n` at `table.remove(lines)` return string.
