### ISSUE TITLE
Auto-start error about nvidia

### ISSUE THREAD

**Issue by grmebdn** [jxai/lean-conky-config#15]
When i set auto start of the script, I cant load NVIDIA GPU info. 
I can start the script manually without error when i use your own user. But it will get the same error on GPU when i start the script by root. 
And the error info is conky: unknown variable '$nvidia'
By the way, my operation system is Ubuntu 20.04

**Comment by jxai** [comment]
Output of `conky -v` would help the diagnosis

**Comment by grmebdn** [comment]
I found out why. 
There is no `cmd: python in my /usr/bin.`
Make a link : `sudo ln -s /usr/bin/python /usr/bin/python3`
It's really a beautiful theme.
Thank you
