### ISSUE TITLE
Just thank you!

### ISSUE THREAD

**Issue by securegh** [jxai/lean-conky-config#16]
Thanks for making this project, you saved humanity so many hours of conky config tweaking. 
This works right away with the best pertinent info display. 
This should be the default config display when installing conky. 
Thanks again for making this, you're awesome!
PS: I added config override `own_window_type = 'desktop',`  so when I use the keyboard shortcut `super+d` I land on the desktop with the conky display.

**Comment by jxai** [comment]
Thanks for the kind words, feedbacks and suggestions are welcome. Desktop mode is the default now.
