### ISSUE TITLE
How to remove sub-components?

### ISSUE THREAD

**Issue by IfGremlinThen** [jxai/lean-conky-config#18]
I hope this isn't an inappropriate use of the issue system, but suppose I wanted to remove the "swap" MEMORY bar, or the STORAGE graphs, but keep the remaining information.
How would I go about doing that?

**Comment by rafiksemaan** [comment]
You can simply edit the file <lean-conky-path>/lib/components/core.lua

look at this part "lcc.tpl.storage" for storage graphs && "lcc.tpl.memory" for swap memory bar
