### ISSUE TITLE
2 GPUs showing misalignment

### ISSUE THREAD

**Issue by yuan9jie** [jxai/lean-conky-config#21]
First, thank you.
I have two GPUs, and after adding the display, they were a bit misaligned. How to solve it? Thanks
![1](https://github.com/jxai/lean-conky-config/assets/48037262/78d17159-b82d-4d23-a04d-a26644931135)

**Comment by pedrosimao** [comment]
how do you show 2 GPUs. I only get one one of them....

**Comment by jxai** [comment]
> how do you show 2 GPUs. I only get one one of them....
LCC GPU module might be running the Conky backend on your system, while only the [`pynvml` backend](https://github.com/jxai/lean-conky-config#gpu-support) supports multiple GPUs. To check if `pynvml` backend can discover all GPUs, run `/path/to/lcc/lib/components/gpu_nvml`.

**Comment by jxai** [comment]
Fixed by commit 652367c7 which improves support for multiple GPUs.
