### ISSUE TITLE
How can I specify mountpoints to show?

### ISSUE THREAD

**Issue by nilp0inter** [jxai/lean-conky-config#22]
Hi,

My conky is only showing `/boot`, I suspect it's because I am using ZFS for the rest of the mountpoins.  Anyway, I have a lot of mountpoints and it would be nice
 to specify a list of mountpoints to restrict what is shown.

Is that possible?

![image](https://github.com/jxai/lean-conky-config/assets/1224006/63411d34-6ac7-4d46-9391-458441857b46)

**Comment by buck2202** [comment]
I was poking around in the code for a related reason (_hiding_ bind mounts), and I think you can get what you want by modifying `utils.enum_disks()` in `utils.lua`

It just parses the output of findmnt, filtered down to specific filesystem types https://github.com/jxai/lean-conky-config/blob/27aeeb9c793ad3da8d1da9b777522eef9000e2df/lib/utils.lua#L130-L134

Probably just add `zfs` to the types list to start? But `findmnt -bPUno TARGET,FSTYPE,SIZE,USED` (with no fs filter), should tell you for sure what you need to add

**Comment by jxai** [comment]
LCC now has options to customize mountpoints, please check [the doc](https://github.com/jxai/lean-conky-config#customize-storage-mountpoints) and `local.conf.example`. `zfs` was also included in the default filesystem types.
