### ISSUE TITLE
No External Drives showing

### ISSUE THREAD

**Issue by SeaDaddytheRed** [jxai/lean-conky-config#33]
Hello,  I am on the latest Zorin OS and am unable to see any of my external drives in Lean Conky.

I recently switched from Windows so all my external drives are still NTFS. Is the automatic detection not compatible with ntfs drives?

Thank you for any help.

**Comment by buck2202** [comment]
(duplicating https://github.com/jxai/lean-conky-config/issues/22#issuecomment-2211157208 on a related issue)

I was poking around in the code for a related reason (_hiding_ bind mounts), and I think you can get what you want by modifying `utils.enum_disks()` in `utils.lua`

It just parses the output of findmnt, filtered down to specific filesystem types https://github.com/jxai/lean-conky-config/blob/27aeeb9c793ad3da8d1da9b777522eef9000e2df/lib/utils.lua#L130-L134

Maybe add `ntfs-3g` (or whatever you're using) to the types list to start?


But FWIW, my (permanent) ntfs mounts get caught as `fuseblk`. You can check the output of `findmnt -bPUno TARGET,FSTYPE,SIZE,USED` and see if your missing mounts are in there, and why they might be getting filtered out

**Comment by SeaDaddytheRed** [comment]
Thank you for the advice.

I tried adding ntfs, and ntfs-3g, but neither gave me any luck.

BUT, I did add exfat which made my one exfat formatted drive show up on lean.

Then I tried findmnt and saw my ntfs drives listed as FSTYPE="ntfs3".  So adding "ntfs3" to the fs_types fixed it!

Thank you again for you help!

**Comment by SeaDaddytheRed** [comment]
If I could just ask one more thing?

Is there a way to get the used space to display in GiB even if the hdd is larger than 1TiB?

**Comment by buck2202** [comment]
There's probably a cleaner way to do this, but at a glance you can edit `filesize` in `lib/external/filesize.lua`

Change https://github.com/jxai/lean-conky-config/blob/27aeeb9c793ad3da8d1da9b777522eef9000e2df/lib/external/filesize.lua#L73-L76
to
```
        -- Exceeding supported length, time to reduce & multiply
        if o.exponent > 3 then
            o.exponent = 3
        end
```

This could _probably_ be done in a cleaner, less-permanent way via a new config argument, but my lua/conky familiarity isn't the best. Works for me in a pinch, though
![image](https://github.com/jxai/lean-conky-config/assets/2069200/a7265f11-b8ab-41b2-89c8-aeac7875336b)

(edited out unnecessary changes)

**Comment by SeaDaddytheRed** [comment]
Thank you!  It works well enough for me.

Next I am going to try and get the following information for each hdd.

Name - Total Space - Free Space - [fs_type] - Percentage

It just makes more sense to me to see how many GiB you have left at a glance than total used.  My external HDD are constantly being filled and I would rather see just how much space I have left at a quick glance.

**Comment by jxai** [comment]
Added options to customize mountpoints, please check [the doc](https://github.com/jxai/lean-conky-config#customize-storage-mountpoints) and `local.conf.example`. `ntfs3` was added to the default filesystem types as well.
