### ISSUE TITLE
External IP Showing IPv6 instead of IPv4

### ISSUE THREAD

**Issue by Dyonovan** [jxai/lean-conky-config#35]
![image](https://github.com/user-attachments/assets/214e425d-8af4-4c23-9862-6eebd79751b7)

Is there anyway to make it show my external IPv4 address which is more useful then the IPv6 address.

**Comment by Dyonovan** [comment]
Figured out how to do it. For anyone else who whats to know. Basically just change the website it grabs the IP from.:

On line 243 of lib/components/core.lua replace

`${alignr}${texeci 3600  wget -q -O- https://ipecho.net/plain; echo}`

with 

`${alignr}${texeci 3600  wget -q -O- https://checkip.amazonaws.com/; echo}`

**Comment by jxai** [comment]
Thanks, fixed in master with e8f9c33aa79e7d88908aedb77a3a355e7cd1ddd0
Missed this issue.
