### ISSUE TITLE
Want to know how to have the "STORAGE" section show ..

### ISSUE THREAD

**Issue by anizee** [jxai/lean-conky-config#4]
Love your config, just wanted to change 1 thing, and have the "STORAGE" section show everything from "/mnt/data" instead of "/". How would I do that?

**Comment by jxai** [comment]
Thanks. Can you post a screenshot so I can know the exact issue you have? You might want to mark off info you think sensitive.

**Comment by anizee** [comment]
Thank you for responding!

I have a drive named "data".  Im wondering if I can get the storage section in CONKY to show the info from that drive instead of the default "/"

![Screen Shot 2021-09-07 at 11 14 30 AM](https://user-images.githubusercontent.com/29491589/132369416-999d9851-f5d7-4a6d-8441-d2e1d34cfd3a.png)

**Comment by anizee** [comment]
any suggestions?
