### ISSUE TITLE
Support Use of AppImage

### ISSUE THREAD

**Issue by alexanderdavide** [jxai/lean-conky-config#7]
## Apparent bug
The current approach merely works with `conky` installed as system package but fails with the AppImage that is proposed in the [instructions](https://github.com/brndnmtthws/conky#quickstart).

## Environment
`conky`: AppImage

## Suggestion
Just an idea: Add a note in `README` to install `conky` as system package or to place the AppImage in the folder of `lean-conky-config`. Then you could detect which one to use in `start.sh`. Alternatively, download the AppImage automatically if the user approves.

**Comment by jxai** [comment]
LCC now supports custom conky installations, just pass the path to your conky binary with the `-p` option. Check [README](https://github.com/jxai/lean-conky-config#use-appimage-or-a-custom-conky-binary) for details.
