### ISSUE TITLE
Downspeedgraph and upspeedgraph in main.lua file, are not working in the latest versions of Conky

### ISSUE THREAD

**Issue by johnvranos** [jxai/lean-conky-config#8]
Good afternoon,

lean-conky is great, you have done a great job.

Unfortunately, downspeedgraph and upspeedgraph in **main.lua** file, are not working since version 1.11 of Conky.

The equivalent boxes in the lean-conky widget remain empty.

I had to compile and install Conky 1.10, for it to work.

I tested downspeegraph and upspeedgraph in conky.conf, and they work there in the latest versions of Conky, but **not** the ones in **main.lua**.

**Comment by johnvranos** [comment]
As mentioned in an answer, to my relevant bug report in Conky, the issue of Lean Conky widget, is fixed, by adding the statement:

store_graph_data_explicitly = false

in your widget conky.conf file.

I tested it, and it works with the latest version of Conky.

**Comment by johnvranos** [comment]
When you add that statement in conky.conf, please close this bug report.

**Comment by johnvranos** [comment]
The problem was fixed with Conky version 1.17:

https://github.com/brndnmtthws/conky/issues/1307


But you must add:

store_graph_data_explicitly = false

in the conky.conf file, of lean-conky-config.

**Comment by jxai** [comment]
Thanks for the pointer, fixed with 060bc5fe.
